Limit Azure IoT Hub downlink retries
brocaar/chirpstack-network-server pull request #603
Opened 2023-05-18 23:52 UTC by jburhenn

If the publishCommand function for Azure IoT Hub gets an error when sending a cloud-to-device message it retries forever so it may never finish. This change adds a retry limit to prevent that. It also adds a test case for testing Azure IoT Hub downlinks.

2023-05-19 10:02 UTC, brocaar requested changes

2023-05-19 10:02 UTC, brocaar commented on internal/backend/gateway/azureiothub/azureiothub_test.go
> +package azureiothub
Unless `TEST_AZURE_IOT_HUB_EVENTS_CONNECTION_STRING` and `TEST_AZURE_IOT_HUB_COMMANDS_CONNECTION_STRING` env variables exist, this tests would fail. Maybe a build tag should be added to explicitly enable this test?

```
// +build integration
```

2023-05-19 15:55 UTC, jburhenn commented on internal/backend/gateway/azureiothub/azureiothub_test.go
> +package azureiothub
Added integration build tag.

2023-05-19 17:30 UTC, asanchezdelc commented
@brocaar Another thing we observed is that when the limit is reached for a particular device, IoT Hub returns the error below and endlessly retries connecting to IoT Hub even though is not a "connection" error. For now this is more of a immediate hotfix, lookout for another PR later on that actually checks for Device Queue Limit. 
<img width="1344" alt="Screenshot 2023-05-17 at 11 56 15 AM" src="https://github.com/brocaar/chirpstack-network-server/assets/552583/db43aeef-c71b-4834-a559-00879d5bd316">

2023-05-19 22:01 UTC, jburhenn commented
Added a change for the queue limit exceeded error. Now it only recreates the sender link instead of doing a full reconnection since that error doesn't require a reconnect.

2025-05-02 09:44 UTC, brocaar commented
I'm going to close this as ChirpStack v3 is no longer in development and I'm going to mark this repository as archived. ChirpStack v4 has been out for more than 2 years and contains many (performance) improvements. ChirpStack v3 users are encouraged to migrate to v4 (https://www.chirpstack.io/docs/v3-v4-migration.html).

2025-05-02 09:44 UTC, closed without merging